# Site settings
title: Spik3s Design
email: web@spik3s.com
description: >
  Web design, programming & DIY jamming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spik3s.com" # the base hostname & protocol for your site
twitter_username: spik3s
github_username:  spik3s

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://spik3s.com'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""